### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by brumar** [brumar/anknotes#22]
Taken from https://anki.tenderapp.com/discussions/add-ons/14451-evernote-importer-error 
```
Traceback (most recent call last): 
  File "C:\Users\F\AppData\Roaming\Anki2\addons\anknotes\__main__.py", line 335, in main 
    controller.proceed() 
  File "C:\Users\F\AppData\Roaming\Anki2\addons\anknotes\__main__.py", line 272, in proceed 
    n = self.import_into_anki(cards_to_add, self.deck, self.ankiTag) 
  File "C:\Users\F\AppData\Roaming\Anki2\addons\anknotes\__main__.py", line 296, in import_into_anki 
    number = self.anki.add_evernote_cards(cards, deck, tag) 
  File "C:\Users\F\AppData\Roaming\Anki2\addons\anknotes\__main__.py", line 55, in add_evernote_cards 
    self.add_note(deck, model_name, anki_field_info, card.tags) 
  File "C:\Users\F\AppData\Roaming\Anki2\addons\anknotes\__main__.py", line 85, in add_note 
    collection.addNote(note) 
  File "anki\collection.py", line 253, in addNote 
  File "anki\notes.py", line 50, in flush 
  File "anki\notes.py", line 113, in stringTags 
  File "anki\tags.py", line 167, in canonify 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

**Comment by brumar** [comment]
I am trying to fix it in the bugfix branch with this commit. https://github.com/brumar/anknotes/commit/b43e6be1ef51c7764556e2e9537dccfe113ffc4c 
I could not reproduce the error. If anyone passing by has this problem, can you replace __main__.py in the anknotes folder (itself in your addons folder) by this file : https://raw.githubusercontent.com/brumar/anknotes/bugfix/anknotes/__main__.py (right-click > save as).

**Comment by brumar** [comment]
According to the poster of this bug, this fixed his problem.
