### ISSUE TITLE
Anki >> Tools >> Import from Evernote

### ISSUE THREAD

**Issue by zaphodbblrx** [brumar/anknotes#24]
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/Users/abomb/Library/Application Support/Anki2/addons/anknotes/__main__.py", line 334, in main
    controller = Controller()
  File "/Users/abomb/Library/Application Support/Anki2/addons/anknotes/__main__.py", line 261, in __init__
    self.evernote = Evernote()
  File "/Users/abomb/Library/Application Support/Anki2/addons/anknotes/__main__.py", line 189, in __init__
    request_token = client.get_request_token('http://brunomart.in/anknotes/index.html')
  File "/Users/abomb/Library/Application Support/Anki2/addons/anknotes/evernote/api/client.py", line 37, in get_request_token
    resp, content = client.request(request_url, 'GET')
  File "/Users/abomb/Library/Application Support/Anki2/addons/anknotes/oauth2/__init__.py", line 683, in request
    connection_type=connection_type)
  File "httplib2/__init__.pyc", line 1597, in request
  File "httplib2/__init__.pyc", line 1345, in _request
  File "aqt/sync.pyc", line 467, in _conn_request
  File "httplib2/__init__.pyc", line 1013, in connect
  File "httplib2/__init__.pyc", line 80, in _ssl_wrap_socket
  File "ssl.pyc", line 943, in wrap_socket
  File "ssl.pyc", line 552, in __init__
IOError: [Errno 20] Not a directory

**Comment by linibazhangyuan** [comment]
I have the same issue

**Comment by brumar** [comment]
That's puzzling. Sorry about that. Do you use Anki 2.0  It seems that it's at the moment of the HTTP request (even if the error is quite weird). Do you know if Anki has been authorized by the firewall ? A user got this kind of problem.

**Comment by Zhengquan** [comment]
Have the same problem. 
Here is the detail version of Anki:
- Version 2.0.50
- Qt 4.8.2 PyQt 4.9.4

**Comment by brumar** [comment]
Damned.
Are you on MacOS too ?

**Comment by zaphodbblrx** [comment]
I'm on MacOS. Is that a clue? I try if it the error replicates on Win10
guest on Vbox today. If it doesn't. That would the workaround.

**Comment by zaphodbblrx** [comment]
It works fine on Win10 guest on MacOS. Images embedded in notes don't seem to synchronize though. Do you think this could added in some future version? Thanks!

**Comment by brumar** [comment]
The image problem is referenced in issue #25 . I can't work on it at the moment. Concerning this MacOS problem, I have no clue either and lack time to investigate. I am sorry but you will need some patience here :(. In case you don't know, an interesting fork for MacOS has been made a while ago. Have anyone here tried it ? https://github.com/rbuc/Evernote2AnkiMac

**Comment by zaphodbblrx** [comment]
I'll give the fork a try. It promises to import images as well. Thank you!
